remote_theme: "just-the-docs/just-the-docs"
title: "OSCP Notes"
description: "Documentation for my OSCP Notes"

# This tells Jekyll where the site lives in the subfolder
baseurl: "/oscp-notes" 
url: "https://AryaReddyvari.github.io"
