remote_theme: "just-the-docs/just-the-docs"
title: "Arya's OSCP Notes"
baseurl: "/oscp-notes"
url: "https://AryaReddyvari.github.io"

# Enable the search bar
search_enabled: true

# Navigation settings
nav_sort: "order"
